version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:7.2.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - type: bind
        source: ./configs/elasticsearch
        target: /usr/share/elasticsearch/config
  logstash:
    image: logstash:7.2.0
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    volumes:
      - type: bind
        source: ./configs/logstash/pipeline
        target: /usr/share/logstash/pipeline
      - type: bind
        source: ./configs/logstash/config
        target: /usr/share/logstash/config
  kibana:
    image: kibana:7.2.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    volumes:
      - type: bind
        source: ./configs/kibana
        target: /usr/share/kibana/config

